import ShouldGo1 from "public/assets/shouldgo-1.png";
import ShouldGo2 from "public/assets/shouldgo-2.png";
import ShouldGo3 from "public/assets/shouldgo-3.png";

export const places = [
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo1.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
    destinationType: "Vườn bách thảo",
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo2.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo3.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo2.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo1.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
    destinationType: "Vườn bách thảo",
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo2.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo3.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo2.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo1.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
    destinationType: "Vườn bách thảo",
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo2.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo3.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo2.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo1.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
    destinationType: "Vườn bách thảo",
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo2.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo3.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo2.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo1.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
    destinationType: "Vườn bách thảo",
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo2.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo3.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo2.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo1.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
    destinationType: "Vườn bách thảo",
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo2.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo3.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo2.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo1.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
    destinationType: "Vườn bách thảo",
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo2.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo3.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo2.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo1.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
    destinationType: "Vườn bách thảo",
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo2.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo3.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo2.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo1.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
    destinationType: "Vườn bách thảo",
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo2.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo3.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo2.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo1.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
    destinationType: "Vườn bách thảo",
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo2.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo3.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo2.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo1.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
    destinationType: "Vườn bách thảo",
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo2.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo3.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo2.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo1.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
    destinationType: "Vườn bách thảo",
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo2.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo3.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo2.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo1.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
    destinationType: "Vườn bách thảo",
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo2.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo3.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo2.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo1.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
    destinationType: "Vườn bách thảo",
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo2.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo3.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo2.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo1.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
    destinationType: "Vườn bách thảo",
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo2.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo3.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
  {
    code: "F2469WER",
    content: "Contrary to popular belief, Lorem Ipsum is not ...",
    background: ShouldGo2.src,
    rating: 4.8,
    ratingCount: 1923,
    toCome: 738,
  },
];
